services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'P@55word!'
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    volumes:
      - ./init.sql:/init/init.sql
      - ./entrypoint.sh:/entrypoint.sh
      - ./mssql-data:/var/opt/mssql/data
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
