apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-ingress
  labels:
    name: microservice-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.example.com
    secretName: tls-secret
  rules:
  - host: api.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/api/customer"
        backend:
          service:
            name: customers
            port:
              number: 8080
      - pathType: Prefix
        path: "/api/order"
        backend:
          service:
            name: orders
            port:
              number: 8080
      - pathType: Prefix
        path: "/api/product"
        backend:
          service:
            name: products
            port:
              number: 8080
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port:
              number: 80
